### ISSUE TITLE
Wrong defaults in MarkdownBear

### ISSUE THREAD

**Issue by plaindocs** [coala/bear-docs#19]
I'm using MarkdownBear without setting any options, and it looks like the defaults in the docs are wrong. I'll dig around and see if I can come up with a full list.

**Comment by sils** [comment]
that sounds interesting, the docs are generated, maybe we changed them and the docs are for the next release or something?

**Comment by plaindocs** [comment]
Mmm, sounds possible. 

* coala `0.8.1`
* remark: 6.2.0, remark-cli: 2.1.0
* pretty empty `.coafile` 

markdown_loose_tables	Whether to use pipes for the outermost borders in a table. (Optional, defaults to 'False'.)

Is failing my build. 

The options date from June, acf864659e9218266c1ad349ffdbd251cd811f48

**Comment by adtac** [comment]
So [this](https://github.com/coala/coala-bears/blob/cab58061e30a590f158eb1783b260dec5a7c19d7/bears/markdown/MarkdownBear.py) is the 0.8.1 version of MarkdownBear. And since then `markdown_loose_tables` hasn't changed.

@plaindocs could you please explain exactly what goes wrong with your version and coafile? Thanks.

**Comment by sils** [comment]
@plaindocs please reopen if this is still an issue, we have done a new release since and according to @adtac everything should be alright.
